name: swift-gltf-viewer
options:
    bundleIdPrefix: ${SAMPLE_CODE_DISAMBIGUATOR}.google.filament.swift-gltf-viewer
include: ../app-template.yml
targets:
    swift-gltf-viewer:
        sources: swift-gltf-viewer/
        info: 
          path: Info.plist
        sources:
            - path: 'Download.glb'
              buildPhase: resources
            # - path: 'generated/default_env/default_env_ibl.ktx'
            #   buildPhase: resources
            #   optional: true
            # - path: 'generated/default_env/default_env_skybox.ktx'
            #   buildPhase: resources
            #   optional: true
        templates:
            - FilamentApp
        # preBuildScripts:
        #     - path: build-resources.sh
        #       name: Build Resources
        #       inputFiles:
        #         - $(SRCROOT)/../../../../third_party/environments/lightroom_14b.hdr
        #       outputFiles:
        #         - $(SRCROOT)/generated/default_env/default_env_ibl.ktx
        #         - $(SRCROOT)/generated/default_env/default_env_skybox.ktx

