name: Build

on:
  workflow_dispatch:
    inputs:
      version:
          description: 'Filament Version'
          required: true
          type: string

jobs:
  update-filament:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download latest filament and generate library files
        run: |
          ./release.sh -v ${{ inputs.version }}  -t release
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions